'use strict';

const path  = require('path');
const pkg   = require('./package.json');

const dir = {
    src: 'src',
    pkg: 'dist',
    built: 'built',
    doc: 'docs',
    task: 'tasks',
    test: 'tests',
    types: '@types',
};

const lib = {
    namespace: 'cdp',
    script: pkg.name + '.js',
    d_ts: pkg.name + '.d.ts',
    bundle_d_ts: 'index.d.ts',
};

const d_ts_bundle = {
    name: pkg.name,
    main: path.join(dir.built, lib.d_ts),
    baseDir: dir.built,
    out: path.join('..', dir.pkg, dir.types, pkg.name, lib.bundle_d_ts),
    externals: false,
    verbose: false,
};

const banner = {
    fileName: 'BANNER',
    d_ts_desc: '\n * This file is generated by the CDP package build process.',
};

const submodules = {
    root: 'submodules',
    modules: [
        'cdp-lib',
    ],
};

const libmodules = {
    root: '..',
    modules: [
        'cdp-lib',
    ],
};

// project configuration
module.exports = {

    pkg: pkg,
    dir: dir,
    lib: lib,

    dts_bundle: d_ts_bundle,

    banner: banner,

    submodules: submodules,
};
